# Generated by Django 5.2 on 2025-04-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_birthdate_user_country_user_facebook_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_profile',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
