# Generated by Django 3.2.25 on 2025-04-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='activation_token_created',
            field=models.DateTimeField(null=True),
        ),
    ]
