# Generated by Django 3.2.25 on 2025-04-09 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_register_activation_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(default='0000000000', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_img',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
