# Generated by Django 3.2.25 on 2025-04-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20250409_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='user/images/', verbose_name='photo'),
        ),
    ]
